# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npx cordova prepare
    - run: npx gulp
    - run: npx cordova build android --release
    - name: Sign apks
      run:
        base64 "${{KEYSTORE}}" > mykey.keystore
        jarsigner.exe -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore mykey.keystore ./platforms/android/app/build/outputs/apk/release/*.apk ${{KEYALIAS}} -storepass ${{KEYPASS}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./platforms/android/app/build/outputs/apk/
      

